# Generated by Django 3.0.3 on 2020-03-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NET', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth',
            old_name='login',
            new_name='username',
        ),
    ]
