# Generated by Django 3.0.3 on 2020-03-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NET', '0002_auto_20200311_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_text', models.TextField()),
                ('user', models.TextField()),
                ('ev_time', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Auth',
            new_name='Users',
        ),
    ]
