# Generated by Django 3.0.3 on 2020-03-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NET', '0003_auto_20200319_0928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
