# Generated by Django 3.0.3 on 2020-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NET', '0004_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.TextField()),
                ('d_type', models.CharField(choices=[('None', 'Введите тип устройства'), ('cr', 'Cisco Router'), ('cs', 'Cisco Switch'), ('l', 'Linux'), ('w', 'Windows'), ('p', 'Поток'), ('u', 'Неизвестное устройство')], max_length=4)),
            ],
        ),
    ]
